### ISSUE TITLE
Aliases with more than one destination do not work

### ISSUE THREAD

**Issue by kaiyou** [kaiyou/freeposte.io#19]
When editing an alias, the select list is not prefilled with the alias destination.

**Comment by kaiyou** [comment]
I renamed the issue to better describe the bug. When editing an alias with multiple destinations, only the first email address is saved. This could be related to using ``select2`` for aliases.

**Comment by jkarlosb** [comment]
I was debugging for this issue and I found that the problem is due to use `SelectField` instead [SelectMultipleField](http://wtforms.simplecodes.com/docs/0.6.1/fields.html#wtforms.fields.SelectMultipleField) into class `AliasForm()` of `forms.py`:

```
class AliasForm(Form):
    localpart = fields.StringField('Alias', [validators.DataRequired()])
    destination = fields.SelectField('Destination')
    comment = fields.StringField('Comment')
    submit = fields.SubmitField('Create')
```
Because I noticed that in aliases.py, the method form.populate_obj(alias) into edit_alias() only populated one destination, data field instead raw_data field. After I changed to SelectMultipleField, data field contains multiple destinations. 

But the problem is that database is not prepared for this change because is necessary introducing an array in the destination field of alias table, this is it sql schema:

```
CREATE TABLE alias (
	created_at DATE NOT NULL,
	updated_at DATE,
	comment VARCHAR(255),
	localpart VARCHAR(80) NOT NULL,
	destination VARCHAR NOT NULL,
	domain_name VARCHAR(80) NOT NULL,
	email VARCHAR(255) NOT NULL,
	PRIMARY KEY (email),
	FOREIGN KEY(domain_name) REFERENCES domain (name)
);
```

And this is the output error when I try add multiples detinations with SelectMultipleField:

```
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 1 - probably unsupported type. [SQL: 'UPDATE alias SET updated_at=?, destination=? WHERE alias.email = ?'] [parameters: ('2016-08-11', ['alias1@mydomain.com', 'alias2@mydomain.com'], 'me@mydomain.com')]

```

As this bd is SQLite, we must add a relational table. Other solutions are using BLOB (as a workaround) or using no-sql db as MongoDB (maybe the optimal solution, because it support arrays as type). 

Another problem is how to query Postfix aliases ...

Meanwhile there is a workaround here (#34)

I can handle this by creating a new branch, but I need to know how proceded with this problem.

How do yo see it?

**Comment by kaiyou** [comment]
There are two problems with using a relational table : 
1. it adds complexity without improving performance (either storage or access performance)
2. postfix will be fine with a database accessed relational table but we would have to implement a different scheme for redictions because Dovecot does not support relational tables at all.

**Comment by kaiyou** [comment]
Prior to using Select2 we were using tagsinput (https://github.com/kaiyou/freeposte.io/commit/4853e54f0b9638d4c031e357a74e707179609318) which worked perfectly because it stored a comma separated list (Postfix compatible format) and read from the same list.

Maybe Select2 supports this as well, which would make for the simplest fix at stay compatible with both Postfix and Dovecot.

**Comment by kaiyou** [comment]
I just pushed a commit that implements : 
- a WTForm field class that handles validation based on the ``SelectMultipleField`` that you suggested,
- a database type for comma separated lists to keep the Postfix compatibility without adding the complexity of a relation table.

What do you think of it? Still testing the forwarding part locally but it seems to fix the bug at least.

**Comment by jkarlosb** [comment]
Great work! It is perfect and simply for now.

I pulled the latest automatic build freeposte/admin image and I tested it with a couple of destinations and It works fine. Congrats!

**Comment by kaiyou** [comment]
Thank you for your feedback, I'm closing the issue then.
